// @generated by protoc-gen-connect-es v1.2.0 with parameter "target=ts"
// @generated from file proto/api/v1/server.proto (package proto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { ListResponse, RunOneshotRequest, RunOneshotResponse } from "./server_pb.js";

/**
 * @generated from service proto.api.v1.RunnerService
 */
export const RunnerService = {
  typeName: "proto.api.v1.RunnerService",
  methods: {
    /**
     * @generated from rpc proto.api.v1.RunnerService.List
     */
    list: {
      name: "List",
      I: Empty,
      O: ListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.api.v1.RunnerService.RunOneshot
     */
    runOneshot: {
      name: "RunOneshot",
      I: RunOneshotRequest,
      O: RunOneshotResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

