version: '3'
services:
  frontend:
    image: ${PROCLET_IMAGE_ROOT}/frontend:latest
    container_name: frontend
    ports:
      - 80:80
  backend:
    image: ${PROCLET_IMAGE_ROOT}/frontend:latest
    container_name: backend
    command: /app/bin/koya server --uid 1001 --gid 1001
    volumes:
      # NOTICE: Use the same docker socket as the host
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    ports:
      - 9000:9000
