// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: proto/api/v1/server.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KoyaServiceClient is the client API for KoyaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KoyaServiceClient interface {
	RunOneshot(ctx context.Context, in *RunOneshotRequest, opts ...grpc.CallOption) (KoyaService_RunOneshotClient, error)
}

type koyaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKoyaServiceClient(cc grpc.ClientConnInterface) KoyaServiceClient {
	return &koyaServiceClient{cc}
}

func (c *koyaServiceClient) RunOneshot(ctx context.Context, in *RunOneshotRequest, opts ...grpc.CallOption) (KoyaService_RunOneshotClient, error) {
	stream, err := c.cc.NewStream(ctx, &KoyaService_ServiceDesc.Streams[0], "/v1.KoyaService/RunOneshot", opts...)
	if err != nil {
		return nil, err
	}
	x := &koyaServiceRunOneshotClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KoyaService_RunOneshotClient interface {
	Recv() (*RunOneshotResponse, error)
	grpc.ClientStream
}

type koyaServiceRunOneshotClient struct {
	grpc.ClientStream
}

func (x *koyaServiceRunOneshotClient) Recv() (*RunOneshotResponse, error) {
	m := new(RunOneshotResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KoyaServiceServer is the server API for KoyaService service.
// All implementations must embed UnimplementedKoyaServiceServer
// for forward compatibility
type KoyaServiceServer interface {
	RunOneshot(*RunOneshotRequest, KoyaService_RunOneshotServer) error
	mustEmbedUnimplementedKoyaServiceServer()
}

// UnimplementedKoyaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKoyaServiceServer struct {
}

func (UnimplementedKoyaServiceServer) RunOneshot(*RunOneshotRequest, KoyaService_RunOneshotServer) error {
	return status.Errorf(codes.Unimplemented, "method RunOneshot not implemented")
}
func (UnimplementedKoyaServiceServer) mustEmbedUnimplementedKoyaServiceServer() {}

// UnsafeKoyaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KoyaServiceServer will
// result in compilation errors.
type UnsafeKoyaServiceServer interface {
	mustEmbedUnimplementedKoyaServiceServer()
}

func RegisterKoyaServiceServer(s grpc.ServiceRegistrar, srv KoyaServiceServer) {
	s.RegisterService(&KoyaService_ServiceDesc, srv)
}

func _KoyaService_RunOneshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunOneshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KoyaServiceServer).RunOneshot(m, &koyaServiceRunOneshotServer{stream})
}

type KoyaService_RunOneshotServer interface {
	Send(*RunOneshotResponse) error
	grpc.ServerStream
}

type koyaServiceRunOneshotServer struct {
	grpc.ServerStream
}

func (x *koyaServiceRunOneshotServer) Send(m *RunOneshotResponse) error {
	return x.ServerStream.SendMsg(m)
}

// KoyaService_ServiceDesc is the grpc.ServiceDesc for KoyaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KoyaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.KoyaService",
	HandlerType: (*KoyaServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunOneshot",
			Handler:       _KoyaService_RunOneshot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/api/v1/server.proto",
}
